name: tag

on:
  push:
    paths:
      - CustomTutorials-2.1.lua
    branches:
      - master

jobs:
  tag:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - uses: jaliborc/action-general-autotag@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          source_file: "CustomTutorials-2.1.lua"
          extraction_regex: "LibStub:NewLibrary\\(['\\s]+CustomTutorials-2.1['\\s]+,\\s*(\\d+)\\)"
          tag_format: "2.1.{version}"
